AWS_S3_BUCKET_NAME : 'lgfgbucket'
DIRECTORY_KEY : "data/input/recurrent/graded_mtm_combined_entites/"
LOCAL_SAVE_DIR: data/input/graded_mtm_combined_entities
AWS_SAVE_DIR: input/primary/graded_mtm_combined_entities_labeled/