AWS_S3_BUCKET_NAME : 'lgfgbucket'
DIRECTORY_KEY : data/input/recurrent/graded_files/graded_mtm_combined_entites/
LOCAL_SAVE_DIR_DEFAULT: data/input/graded_mtm_combined_entities
LOCAL_SAVE_DIR_LABELED: data/input/graded_mtm_combined_entities_labeled
AWS_SAVE_DIR: data/input/primary/graded_mtm_combined_entities_labeled/
