version : "3"

services:
#UI service
  ui:
    image: lgfg_docker_images:ui
    build:
      dockerfile: UI_Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ".:/app/ui"
# API service
  api:
    image : lgfg_docker_images:api
    build:
      dockerfile: API_Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ".:/app/api"