ALLOWED_EXTENSIONS :
  - 'xlsx'
  - 'csv'
  - 'dxf'
ALLOWED_MIME_TYPES :
  - 'application/vnd.ms -excel'
  - 'image/x-dxf'
  - 'text/csv'
AWS_S3_BUCKET_NAME : 'lgfgbucket'
AWS_DXF_DIR_PATH : "data/input/recurrent/dxf_files/"
AWS_DXF_GRADED_DIR_PATH : "data/input/recurrent/graded_dxf/"
AWS_MTM_DIR_PATH : "data/input/recurrent/mtm_combined_entites/"
AWS_MTM_GRADED_DIR_PATH : "data/input/recurrent/graded_mtm_combined_entites/"
AWS_MTM_DIR_PATH_LABELED : "data/input/primary/mtm_combined_entites_labeled/"
AWS_PLOT_DIR_BASE : "data/plots/base_pieces"
AWS_OUTPUT_DIR_PATH : "data/output"
AWS_S3_SIGNATURE_VERSION : "s3v4"
AWS_PROFILE : "tailoring_api"
DB_TYPE : "postgresql"
DB_API : "psycopg2"
DB_HOST : 127.0.0.1
DB_PORT : 5432
DB_NAME : "lgfg_api"
